version: '3.8'

services:
  postgres:
    image: ankane/pgvector  
    container_name: pgvector-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 01ummilhao
      POSTGRES_DB: banco_vertex_ai
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
